apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: demo-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      version: green
  template:
    metadata:
      labels:
        app: demo-app
        version: green
    spec:
      containers:
      - name: demo-container
        image: efotsowoe/resume-app
        ports:
        - containerPort: 80

